### ISSUE TITLE
bzip2 error message

### ISSUE THREAD

**Issue by bluesteal** [mirage/qubes-mirage-firewall#172]
When following the instructions in the following article:

https://roscidus.com/blog/blog/2016/01/01/a-unikernel-firewall-for-qubesos/#the-xen-virtual-network-layer

There is an error message returned in response to:

tar xf /tmp/mirage-firewall-bin-0.1.tar.bz2

which is:

bzip2: (stdin) is not a bzip2 file

the file is downloaded from the following directory:

https://github.com/mirage/qubes-mirage-firewall/releases/download/v0.8.4/mirage-firewall.tar.bz2

**Comment by palainp** [comment]
This issue seems to be related to a misuse of `qvm-run`/`wget` (see https://github.com/mirage/qubes-mirage-firewall/issues/173#issuecomment-1496724348).

To download the .tar.bz2 directly to dom0, you should use `-q -O -` instead of `-o -` because the lowercase 'o' outputs the logs to stdout, and the uppercase 'O' outputs the data to stdout (and the 'q' turns off the log output because you only want to have the data on stdout).

Therefore, a "correct" qvm-run call should be `qvm-run -p sys-net 'wget -q -O - https://github.com/mirage/qubes-mirage-firewall/releases/download/v0.8.4/mireage-firewall.tar.bz2' > mirage-firewall.tar.bz2`. You can then check the hashsum to be sure you have retrieved the correct unikernel.

And as stated in https://github.com/mirage/qubes-mirage-firewall/issues/84#issue-529473022 you probably don't want to copy the tarball and untar into dom0, but download into an AppVM, untar it and then copy into dom0.

**Comment by palainp** [comment]
Based on https://github.com/mirage/qubes-mirage-firewall/issues/173#issuecomment-1498431316 I think this issue can be closed?

**Comment by hannesm** [comment]
indeed, thanks @palainp for investigating (and spotting `wget -o` vs `wget -O`)
