### ISSUE TITLE
Support Qubes 4 dynamic rules

### ISSUE THREAD

**Issue by talex5** [mirage/qubes-mirage-firewall#24]
Qubes 3 provided the rules in Linux iptables format, which we can't read. However, Qubes 4 apparently provides a cleaner format:

https://www.qubes-os.org/doc/vm-interface/#firewall-rules-in-4x

I'm not on Qubes 4 yet, but if anyone wants to have a go at this now, feel free!

**Comment by cfcs** [comment]
Hi Thomas, I'm currently working on https://github.com/cfcs/ocaml-pf to parse the `pf` rule format from FreeBSD. The parsing mostly works now, but I'm still working on the actual firewall engine (to make decisions based on an incoming package). I hope to make this usable as a plug-in utility that `qubes-mirage-firewall` can use to implement user-supplied rules.

I considered also writing an `iptables` parser, since the syntax seems easier to parse than `pf`, but I'm a bit skeptical re: dynamically/automatically re-configuring rules. The way this currently works in `Qubes 3.2` is brittle and error-prone, and I disagree with how it is implemented (after changing the firewall rules to `block all`, existing *ESTABLISHED* connections are still allowed through, for example, which I find unintuitive and dangerous).

In my personal setup (on 3.2) I do not want bug-for-bug compatibility with the `iptables`/Linux setup Qubes is currently using, so I am afraid that implementing "seamless" handling of their automatic firewall changes will lead to confusion.

That being said, the 4.0 format seems pretty easy to parse, and I think the engine I hacked together for the `json` format should be able to handle the filters they define (very nice link, I had completely missed this page).

I'm going to stay away from 4.0 until it stabilizes a bit though (afaik 3.2 should be supported for another year?).

**Comment by donob4n** [comment]
Hi,

for Qubes 3.2 support I think that best way is backporting Qubes 4.0 format to 3.2, since it uses different qubesdb entries should work fine with both std sys-firewall and mirage-firewall.

**Comment by cfcs** [comment]
FWIW I have a Angstrom-based parser here: https://github.com/cfcs/ocaml-pf/blob/master/lib/parse_qubes.ml

**Comment by talex5** [comment]
That's great! Is there an engine to go with it yet?

**Comment by cfcs** [comment]
There's no `pf` engine yet, no :(

There's my slightly hacky `#user_supplied_rules` branch (of this repo) which does have an engine, so if one just wanted something that worked as a weekend project, I think it shouldn't be too tricky to retrofit that branch with this Qubes4 angstrom parser.

My hope is to at some point have a `pf` engine though, and be able to firewall things in a pf-compatible way (and not just `qubes` either), but that will take quite a bit of work. :(

**Comment by darrenldl** [comment]
@cfcs Hello, I am currently working on a [firewall decision tree library](https://gitlab.com/darrenldl/ocaml-firewall) providing a generic functor, with MirageOS as the primary backend to be supported. @talex5 linked me to this issue at this [thread](https://discuss.ocaml.org/t/access-to-tcp-header-fields-in-mirageos/3497/7) at the forum. (Thanks Thomas!)

The firewall library took inspiration from iptables and pf, and ideally can replicate the behaviour of either in the decision tree, while remaining testable via quickcheck etc.

Is there any update on your progress w.r.t. the `pf` engine?

**Comment by linse** [comment]
Fixed in master.
