### ISSUE TITLE
an upstream tcpip bug breaks ping in latest release

### ISSUE THREAD

**Issue by yomimono** [mirage/qubes-mirage-firewall#50]
The latest `qubes-mirage-firewall` release breaks `ping` from downstream clients, as outbound ICMP echo requests translated by the firewall get an invalid ICMP checksum and are not answered by popular remote servers like 8.8.8.8 .  This isn't the firewall's fault, but once the upstream problem in `tcpip` is fixed and a new version released, the new version should be used to fix this regression.

**Comment by yomimono** [comment]
I'd like to leave this open until a fixed tcpip is released.

**Comment by hannesm** [comment]
i agree. it was github automatically closing this when i merged your tcpip PR...

**Comment by xaki23** [comment]
this seems to be only a partial fix or just uncovers the next part that needs fixing.

testsetup: netvm - mfw - appvm
appvm: ping 8.8.8.8
mfw console: 2019-04-06 13:34:55 -00:00: INF [firewall] Dropped packet (drop by default) [src=net-vm dst=firewall(uplink) proto=ICMP]

== the pong from the target makes it to the mirage-fw, then does _not_ match an existing NAT rule and hits the default-drop at the end of rules.ml.

**Comment by yomimono** [comment]
@xaki23 , try also pinning `mirage-nat` to `https://github.com/mirage/mirage-nat.git#separate-header`, where I'm doing more work with ICMP support.  With both `tcpip` updated to (what will be, when accepted into the opam repository) version 3.7.3 and that development pin, `ping` gets the correct responses.

**Comment by xaki23** [comment]
not sure if the comment should go into #55 or here.
putting it here because #55 is basicly about the official build process(es), but i use qubes-builder.

build now works without any pins.
and the result handles all things icmp i can think of really well.
return-nat of icmp about icmp, udp, tcp.
traceroute with icmp, udp, tcp and various sizes.
and all of that in both truncated and untruncated form. 

so, all in favor of merge and close!

thanks to everyone who contributed. 
this turned out to be a MUCH deeper rabbithole than i expected when opening #31 half a year ago.
with the "oh, thats not me, thats opam being broken in general!" detour this weekend as the icing on the cake at the bottom of the hole... 

again, thanks, and fly safe!
