### ISSUE TITLE
Remove GUI code

### ISSUE THREAD

**Issue by talex5** [mirage/qubes-mirage-firewall#62]
Qubes 3 required us to connect to the GUI daemon in dom0 before it would consider the firewall to have started. Qubes 4 no longer requires this (see `man qvm-features`).

Remove the GUI code from `unikernel.ml` and test/update the installation instructions in `README.md` to make sure they work with the new system.

**Comment by xaki23** [comment]
actualy, more tricky.

even if i set "qvm-features mirage-fw gui ''" ... (warning: two single ticks for "empty value", followed by a doubletick for "quoted string in github ticket") ... the status never fully turns green in qubes-manager.
(the vm works though)

@marmarek pointed out that adding "qvm-features mirage-fw qrexec 1" is "required" there too. (there is an even more complicated optional hamsterdance inside the vm instead of setting the feature)

+1 from me for making this change, and yes, good-beginner-project.

**Comment by palainp** [comment]
Hi, I tried here (https://github.com/palainp/qubes-mirage-firewall/commit/6c040c654cd7dfc82d212a5443e2ab41fa31e625) to just delete the gui code and it compiles+runs fine so far.

Could it be "that simple" (and doesn't currently require some special qvm-features invocation) or am I missing something else? The status is green in qubes-manager, I can see the cpu usage, etc. and the various popups appear when starting or terminating the vm.

**Comment by hannesm** [comment]
@palainp it may very well be that easy (these days). Would you mind to PR your change?

**Comment by hannesm** [comment]
#144 (merged as part of #149) solves this issue.
