### ISSUE TITLE
Clarify impact of QSB #56 on qubes-mirage-firewall

### ISSUE THREAD

**Issue by tetrahedras** [mirage/qubes-mirage-firewall#87]
[QSB 56](https://github.com/QubesOS/qubes-secpack/blob/master/QSBs/qsb-056-2019.txt) is about firewall rules. Is mirage-firewall affected?

**Comment by talex5** [comment]
The issue here is that the default (Linux) sys-firewall does not reject IP packets from sys-net that have an AppVM's IP as their source.

mirage-firewall does not have this problem. The firewall will log messages like this if you try:

```
WRN [firewall] Frame from NetVM has internal source IP address! [src=10.137.0.15 dst=10.137.0.10 proto=ICMP]
```

The code that produces it is here:

https://github.com/mirage/qubes-mirage-firewall/blob/dab790cb68a848c6d09fc03fde226130a4fb08f0/firewall.ml#L192

As the issue notes, there is currently no way to know that an address is internal if the AppVM is not currently running. Once Qubes 4.1 provides that information, mirage-firewall should be updated to use it too.

**Comment by tetrahedras** [comment]
Good to know, thanks!

**Comment by quantumpacket** [comment]
> Once Qubes 4.1 provides that information, mirage-firewall should be updated to use it too.

Does anyone know if that change made it into Qubes 4.1
